version: '3.7'

services:
  vuetify:
    container_name: vuetifyWEB
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: npm run serve
    volumes:
      - '.:/app'
    ports:
      - '8080:8080'